//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbObjLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class acs_event
    {
        public int id_acs_event { get; set; }
        public System.DateTime tx_date_time { get; set; }
        public System.DateTime rx_date_time { get; set; }
        public int id_acs_card { get; set; }
    
        public virtual acs_card acs_card { get; set; }
    }
}
