//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbObjLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class acs_card_state
    {
        public int id_acs_card_state { get; set; }
        public string card_state { get; set; }
        public System.DateTime date_time { get; set; }
        public int id_acs_card { get; set; }
        public int id_person { get; set; }
        public string note { get; set; }
    
        public virtual acs_card acs_card { get; set; }
        public virtual person person { get; set; }
    }
}
