//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbObjLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class acs_event
    {
        public int id_acs_event { get; set; }
        public System.DateTime tx_date_time { get; set; }
        public System.DateTime rx_date_time { get; set; }
        public int id_acs_card { get; set; }
    
        public virtual acs_card acs_card { get; set; }
    }
}
