//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbObjLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TvarditaEntities : DbContext
    {
        public TvarditaEntities()
            : base("name=TvarditaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acs_card> acs_card { get; set; }
        public virtual DbSet<acs_card_state> acs_card_state { get; set; }
        public virtual DbSet<acs_event> acs_event { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<person> people { get; set; }
        public virtual DbSet<person_department_position> person_department_position { get; set; }
        public virtual DbSet<person_rec_fir_state> person_rec_fir_state { get; set; }
        public virtual DbSet<work_position> work_position { get; set; }
    }
}
