//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbObjLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_rec_fir_state
    {
        public int id_prsn_rec_fir_state { get; set; }
        public int id_person { get; set; }
        public System.DateTime date_time_state { get; set; }
        public int id_rec_fir_state { get; set; }
        public string note { get; set; }
    
        public virtual person person { get; set; }
    }
}
