//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbObjLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_department_position
    {
        public int id_prsn_dprtm_pos { get; set; }
        public System.DateTime datetime_pos { get; set; }
        public int id_person { get; set; }
        public int id_department { get; set; }
        public int id_work_position { get; set; }
        public string note { get; set; }
    
        public virtual department department { get; set; }
        public virtual person person { get; set; }
        public virtual work_position work_position { get; set; }
    }
}
