//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbObjLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_department_position
    {
        public int id_prsn_dprtm_pos { get; set; }
        public System.DateTime datetime_pos { get; set; }
        public int id_person { get; set; }
        public int id_department { get; set; }
        public int id_work_position { get; set; }
        public string note { get; set; }
    }
}
