//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbObjLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_rec_fir_state
    {
        public int id_prsn_rec_fir_state { get; set; }
        public int id_person { get; set; }
        public System.DateTime date_time_state { get; set; }
        public int id_rec_fir_state { get; set; }
        public string note { get; set; }
    
        public virtual person person { get; set; }
    }
}
