//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbObjLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_acs_card
    {
        public int id_person_acs_card { get; set; }
        public int id_acs_card { get; set; }
        public int id_person { get; set; }
        public System.DateTime date_time { get; set; }
        public string card_state { get; set; }
        public string note { get; set; }
    
        public virtual acs_card acs_card { get; set; }
        public virtual person person { get; set; }
    }
}
